# Generated by Django 5.2.5 on 2025-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='skill_logos/')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover_img', models.ImageField(blank=True, upload_to='cover_photo/')),
                ('work_btn', models.CharField(max_length=20)),
            ],
        ),
    ]
