# Generated by Django 5.2.5 on 2025-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
