# Generated by Django 5.2.5 on 2025-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_work_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Work', max_length=100)),
                ('subheading', models.TextField(blank=True)),
            ],
        ),
    ]
