# Generated by Django 5.2.5 on 2025-08-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_worksection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('job_title', models.CharField(default='Full Stack Developer', max_length=100)),
                ('heading', models.CharField(default='About', max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='Other', max_length=50)),
                ('icon_class', models.CharField(help_text='e.g. "fa-brands fa-linkedin-in"', max_length=100)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.aboutsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
