# Generated by Django 5.2.5 on 2025-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_remove_sociallink_about_delete_aboutsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('fa-brands fa-html5', 'HTML5'), ('fa-brands fa-css3-alt', 'CSS3'), ('fa-brands fa-js', 'JavaScript'), ('fa-brands fa-java', 'Java'), ('fa-brands fa-python', 'Python'), ('fa-solid fa-c', 'C'), ('fa-brands fa-github', 'Git & GitHub'), ('fa-solid fa-database', 'PLSQL')], help_text='FontAwesome class', max_length=100)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Skill level in %')),
                ('description', models.TextField(blank=True, help_text='Optional skill description', null=True)),
                ('title', models.CharField(blank=True, help_text='Optional skill title', max_length=100, null=True)),
                ('skill_img', models.ImageField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
    ]
