# Generated by Django 5.2.5 on 2025-08-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_img',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
    ]
