# Generated by Django 5.2.5 on 2025-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_skill_description_remove_skill_skill_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('fa-brands fa-html5', 'HTML5'), ('fa-brands fa-css3-alt', 'CSS3'), ('fa-brands fa-js', 'JavaScript'), ('fa-brands fa-java', 'Java'), ('fa-brands fa-python', 'Python'), ('fa-solid fa-c', 'C'), ('fa-brands fa-github', 'Git & GitHub'), ('fa-solid fa-database', 'PLSQL'), ('fa-brands fa-react', 'React'), ('fa-brands fa-node-js', 'Node.js'), ('fa-brands fa-bootstrap', 'Bootstrap'), ('fa-brands fa-sass', 'Sass'), ('fa-brands fa-figma', 'Figma'), ('fa-brands fa-django', 'django')], help_text='FontAwesome class', max_length=100),
        ),
    ]
