# Generated by Django 5.2.5 on 2025-08-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill_img', models.ImageField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
